spring.application.name=order-calculator
server.port=8080
spring.jackson.time-zone=Europe/Moscow

# ============= Firebase =============
firebase.config.path=classpath:serviceAccountKey.json
firebase.project.id=shipments-f48c2

# ============= Wildberries API =============
# Токен API продавца (получить в личном кабинете WB -> Настройки -> Доступ к API)
wb.api.token=
wb.api.base-url=https://suppliers-api.wildberries.ru
wb.api.statistics-url=https://statistics-api.wildberries.ru
wb.api.analytics-url=https://analytics-api.wildberries.ru

# ============= Ozon API — несколько ИП =============
# Формат: список через запятую: clientId1:key1,clientId2:key2,...
ozon.api.accounts=28560:57fd9f69-1931-4633-8186-dec9496a2d09,753500:51e6f7da-1a9f-4109-8756-cc6322768ba4,559028:4b64bc96-65e0-4b64-878a-5440b6771759
ozon.api.base-url=https://api-seller.ozon.ru

# ============= MoySklad API =============
moysklad.api.token=
moysklad.api.base-url=https://api.moysklad.ru/api/remap/1.2